package keys

import "strings"

func GetKeys(str string) []int {
	var result []int
	if strings.TrimSpace(str) == "" {
		return result
	}
	list := strings.Split(str, ",")
	for _, item := range list {
		i := GetKey(item)
		if i != -1 {
			result = append(result, i)
		}
	}
	return result
}

func GetKey(str string) int {
	for k, v := range KeyMap {
		if strings.ToUpper(strings.TrimSpace(str)) == k {
			return v
		}
	}
	return -1
}

const (
	// I add 0xFFF for all Virtual key
	_KEYEVENTF_KEYUP    = 0x0002
	_KEYEVENTF_SCANCODE = 0x0008
)

var KeyMap = map[string]int{
	"SHIFT":               0x10 + 0xFFF,
	"CTRL":                0x11 + 0xFFF,
	"ALT":                 0x12 + 0xFFF,
	"LSHIFT":              0xA0 + 0xFFF,
	"RSHIFT":              0xA1 + 0xFFF,
	"LCONTROL":            0xA2 + 0xFFF,
	"RCONTROL":            0xA3 + 0xFFF,
	"WIN":                 0x5B + 0xFFF,
	"LWIN":                0x5B + 0xFFF,
	"RWIN":                0x5C + 0xFFF,
	"KEYEVENTF_KEYUP":     0x0002,
	"KEYEVENTF_SCANCODE":  0x0008,
	"SP1":                 41,
	"~":                   41,
	"SP2":                 12,
	"-":                   12,
	"SP3":                 13,
	"+":                   13,
	"SP4":                 26,
	"[":                   26,
	"SP5":                 27,
	"]":                   27,
	"SP6":                 39,
	"；":                   39,
	"SP7":                 40,
	"‘":                   40,
	"SP8":                 43,
	"SP9":                 51,
	"，":                   51,
	"SP10":                52,
	"。":                   52,
	"SP11":                53,
	"？":                   53,
	"SP12":                86,
	"ESC":                 1,
	"1":                   2,
	"2":                   3,
	"3":                   4,
	"4":                   5,
	"5":                   6,
	"6":                   7,
	"7":                   8,
	"8":                   9,
	"9":                   10,
	"0":                   11,
	"Q":                   16,
	"W":                   17,
	"E":                   18,
	"R":                   19,
	"T":                   20,
	"Y":                   21,
	"U":                   22,
	"I":                   23,
	"O":                   24,
	"P":                   25,
	"A":                   30,
	"S":                   31,
	"D":                   32,
	"F":                   33,
	"G":                   34,
	"H":                   35,
	"J":                   36,
	"K":                   37,
	"L":                   38,
	"Z":                   44,
	"X":                   45,
	"C":                   46,
	"V":                   47,
	"B":                   48,
	"N":                   49,
	"M":                   50,
	"F1":                  59,
	"F2":                  60,
	"F3":                  61,
	"F4":                  62,
	"F5":                  63,
	"F6":                  64,
	"F7":                  65,
	"F8":                  66,
	"F9":                  67,
	"F10":                 68,
	"F11":                 87,
	"F12":                 88,
	"F13":                 0x7C + 0xFFF,
	"F14":                 0x7D + 0xFFF,
	"F15":                 0x7E + 0xFFF,
	"F16":                 0x7F + 0xFFF,
	"F17":                 0x80 + 0xFFF,
	"F18":                 0x81 + 0xFFF,
	"F19":                 0x82 + 0xFFF,
	"F20":                 0x83 + 0xFFF,
	"F21":                 0x84 + 0xFFF,
	"F22":                 0x85 + 0xFFF,
	"F23":                 0x86 + 0xFFF,
	"F24":                 0x87 + 0xFFF,
	"NUMLOCK":             69,
	"SCROLLLOCK":          70,
	"RESERVED":            0,
	"MINUS":               12,
	"EQUAL":               13,
	"BACKSPACE":           14,
	"TAB":                 15,
	"LEFTBRACE":           26,
	"RIGHTBRACE":          27,
	"ENTER":               28,
	"SEMICOLON":           39,
	"APOSTROPHE":          40,
	"GRAVE":               41,
	"BACKSLASH":           43,
	"COMMA":               51,
	"DOT":                 52,
	"SLASH":               53,
	"KPASTERISK":          55,
	"SPACE":               57,
	"CAPSLOCK":            58,
	"KP0":                 82,
	"KP1":                 79,
	"KP2":                 80,
	"KP3":                 81,
	"KP4":                 75,
	"KP5":                 76,
	"KP6":                 77,
	"KP7":                 71,
	"KP8":                 72,
	"KP9":                 73,
	"KPMINUS":             74,
	"KPPLUS":              78,
	"KPDOT":               83,
	"LBUTTON":             0x01 + 0xFFF,
	"RBUTTON":             0x02 + 0xFFF,
	"CANCEL":              0x03 + 0xFFF,
	"MBUTTON":             0x04 + 0xFFF,
	"XBUTTON1":            0x05 + 0xFFF,
	"XBUTTON2":            0x06 + 0xFFF,
	"BACK":                0x08 + 0xFFF,
	"CLEAR":               0x0C + 0xFFF,
	"PAUSE":               0x13 + 0xFFF,
	"CAPITAL":             0x14 + 0xFFF,
	"KANA":                0x15 + 0xFFF,
	"HANGUEL":             0x15 + 0xFFF,
	"HANGUL":              0x15 + 0xFFF,
	"JUNJA":               0x17 + 0xFFF,
	"FINAL":               0x18 + 0xFFF,
	"HANJA":               0x19 + 0xFFF,
	"KANJI":               0x19 + 0xFFF,
	"CONVERT":             0x1C + 0xFFF,
	"NONCONVERT":          0x1D + 0xFFF,
	"ACCEPT":              0x1E + 0xFFF,
	"MODECHANGE":          0x1F + 0xFFF,
	"PAGEUP":              0x21 + 0xFFF,
	"PAGEDOWN":            0x22 + 0xFFF,
	"END":                 0x23 + 0xFFF,
	"HOME":                0x24 + 0xFFF,
	"LEFT":                0x25 + 0xFFF,
	"UP":                  0x26 + 0xFFF,
	"RIGHT":               0x27 + 0xFFF,
	"DOWN":                0x28 + 0xFFF,
	"SELECT":              0x29 + 0xFFF,
	"PRINT":               0x2A + 0xFFF,
	"EXECUTE":             0x2B + 0xFFF,
	"SNAPSHOT":            0x2C + 0xFFF,
	"INSERT":              0x2D + 0xFFF,
	"DELETE":              0x2E + 0xFFF,
	"HELP":                0x2F + 0xFFF,
	"SCROLL":              0x91 + 0xFFF,
	"LMENU":               0xA4 + 0xFFF,
	"RMENU":               0xA5 + 0xFFF,
	"BROWSER_BACK":        0xA6 + 0xFFF,
	"BROWSER_FORWARD":     0xA7 + 0xFFF,
	"BROWSER_REFRESH":     0xA8 + 0xFFF,
	"BROWSER_STOP":        0xA9 + 0xFFF,
	"BROWSER_SEARCH":      0xAA + 0xFFF,
	"BROWSER_FAVORITES":   0xAB + 0xFFF,
	"BROWSER_HOME":        0xAC + 0xFFF,
	"VOLUME_MUTE":         0xAD + 0xFFF,
	"VM":                  0xAD + 0xFFF,
	"VOLUME_DOWN":         0xAE + 0xFFF,
	"VD":                  0xAE + 0xFFF,
	"VOLUME_UP":           0xAF + 0xFFF,
	"VU":                  0xAF + 0xFFF,
	"MEDIA_NEXT_TRACK":    0xB0 + 0xFFF,
	"MN":                  0xB0 + 0xFFF,
	"MEDIA_PREV_TRACK":    0xB1 + 0xFFF,
	"MP":                  0xB1 + 0xFFF,
	"MEDIA_STOP":          0xB2 + 0xFFF,
	"MSTOP":               0xB2 + 0xFFF,
	"MEDIA_PLAY_PAUSE":    0xB3 + 0xFFF,
	"MPLAY":               0xB3 + 0xFFF,
	"LAUNCH_MAIL":         0xB4 + 0xFFF,
	"LAUNCH_MEDIA_SELECT": 0xB5 + 0xFFF,
	"LAUNCH_APP1":         0xB6 + 0xFFF,
	"LAUNCH_APP2":         0xB7 + 0xFFF,
	"OEM_1":               0xBA + 0xFFF,
	"OEM_PLUS":            0xBB + 0xFFF,
	"OEM_COMMA":           0xBC + 0xFFF,
	"OEM_MINUS":           0xBD + 0xFFF,
	"OEM_PERIOD":          0xBE + 0xFFF,
	"OEM_2":               0xBF + 0xFFF,
	"OEM_3":               0xC0 + 0xFFF,
	"OEM_4":               0xDB + 0xFFF,
	"OEM_5":               0xDC + 0xFFF,
	"OEM_6":               0xDD + 0xFFF,
	"OEM_7":               0xDE + 0xFFF,
	"OEM_8":               0xDF + 0xFFF,
	"OEM_102":             0xE2 + 0xFFF,
	"PROCESSKEY":          0xE5 + 0xFFF,
	"PACKET":              0xE7 + 0xFFF,
	"ATTN":                0xF6 + 0xFFF,
	"CRSEL":               0xF7 + 0xFFF,
	"EXSEL":               0xF8 + 0xFFF,
	"EREOF":               0xF9 + 0xFFF,
	"PLAY":                0xFA + 0xFFF,
	"ZOOM":                0xFB + 0xFFF,
	"NONAME":              0xFC + 0xFFF,
	"PA1":                 0xFD + 0xFFF,
	"OEM_CLEAR":           0xFE + 0xFFF,
}
